# Day 3 Assignment

# question 1

In [2]:
import numpy as np

In [3]:
arr = np.arange(2, 51, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# question 2

In [38]:
l1=list()
l2=list()
print("list1")
for i in range(5):
    a=int(input())
    l1.append(a)
print("list2")
for i in range(5):
    a=int(input())
    l2.append(a)
#print(l2)
arr1 = np.array(l1)
arr2 = np.array(l2)
arr=np.concatenate((arr1,arr2))
print("concatenated array: ",arr)
arr=np.sort(arr)
print("sorted array: ",arr)

list1
2
4
7
12
43
list2
1
53
87
34
56
concatenated array:  [ 2  4  7 12 43  1 53 87 34 56]
sorted array:  [ 1  2  4  7 12 34 43 53 56 87]


# question 3

In [73]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Printing dimensions of array
print("dimension of array:",arr.ndim)
 
# Printing size of array
print("size of array:",arr.size)

dimension of array: 2
size of array: 9


# question 4

In [76]:
print("using np.expand_dims")
a = np.arange(6)
print("1D array:\n",a)
print("dimension:",a.ndim)
b=a[:, np.newaxis]
print("2D array:\n",b)
print("dimension:",b.ndim)

print("\nUsing np.expand_dims")
a = np.arange(6)
print("1D array:\n",a)
print("dimension:",a.ndim)

b=np.expand_dims(a, 1)
print("2D array:\n",b)
print("dimension:",b.ndim)

using np.expand_dims
1D array:
 [0 1 2 3 4 5]
dimension: 1
2D array:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
dimension: 2

Using np.expand_dims
1D array:
 [0 1 2 3 4 5]
dimension: 1
2D array:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
dimension: 2


# question 5

In [36]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(" horizontally stacked: \n", np.hstack((arr1,arr2)))

print("vertically stacked : \n", np.vstack((arr1,arr2)))


 horizontally stacked: 
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
vertically stacked : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


# question 6

In [37]:
arr = np.array([3,6,4,1,8,4,1,1])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[1 3]
 [3 1]
 [4 2]
 [6 1]
 [8 1]]
